export interface RoadmapItem {
  id: string;
  title: string;
  description: string;
  priority: number;
  dependencies?: string[];
  dependsOn?: string[];
}

export function roadmapToMarkdown(items: RoadmapItem[], projectName?: string): string {
  const title = projectName || "Roadmap EchoMaps";
  let md = `# ${title}\n\n`;
  md += `> Generated by EchoMaps on ${new Date().toLocaleDateString("fr-FR")}\n\n`;

  const sorted = [...items].sort((a, b) => a.priority - b.priority);

  for (const item of sorted) {
    const priorityLabel = ["", "Critique", "Haute", "Moyenne", "Basse", "Optionnelle"][item.priority] || "N/A";
    md += `## ${item.title}\n\n`;
    md += `- **Priorite**: ${priorityLabel} (${item.priority}/5)\n`;
    md += `- **Description**: ${item.description}\n`;
    if (item.dependsOn && item.dependsOn.length > 0) {
      md += `- **Depend de**: ${item.dependsOn.join(", ")}\n`;
    }
    md += `\n`;
  }

  return md;
}

export function downloadJSON(data: unknown, filename: string): void {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}
